# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
project 'verifast-sdk-sample-app.xcodeproj'

target 'verifast-sdk-sample-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for verifast-sdk-sample-app
  pod 'eyn', '1.0.5'

end
